version: '3.8'

services:
  reconecta-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reconecta-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - reconecta_db_data:/app/server/data

volumes:
  reconecta_db_data:
    driver: local
